### ISSUE TITLE
TypeError: DownloadAndLoadFYEModel.loadmodel() got an unexpected keyword argument 'motion_model'

### ISSUE THREAD

**Issue by feifeiye** [kijai/ComfyUI-FollowYourEmojiWrapper#3]
装上后正常运行了一遍，但是关掉comfyui，再次运行的时候就出现这样的错误了

[AnimateDiffEvo] - INFO - Loading motion module mm_sd_v15_v2.safetensors via Gen2
!!! Exception during processing!!! DownloadAndLoadFYEModel.loadmodel() got an unexpected keyword argument 'motion_model'
Traceback (most recent call last):
  File "D:\ComfyUI-feifei\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-feifei\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-feifei\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DownloadAndLoadFYEModel.loadmodel() got an unexpected keyword argument 'motion_model'

**Comment by kijai** [comment]
Update to the latest workflow, the motion model is no longer loaded separately.
